
services:
  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    networks:
      - backend
    # volumes:
    #   - ./ngrinder-controller:/opt/ngrinder-controller

  agent1:
    image: ngrinder/agent
    restart: always
    links:
      - controller
    networks:
      - backend

  agent2:
    image: ngrinder/agent
    restart: always
    links:
      - controller
    networks:
      - backend

  agent3:
    image: ngrinder/agent
    restart: always
    links:
      - controller
    networks:
      - backend

  agent4:
    image: ngrinder/agent
    restart: always
    links:
      - controller
    networks:
      - backend

  agent5:
    image: ngrinder/agent
    restart: always
    links:
      - controller
    networks:
      - backend
